---
abstract: 'Create Debian or RPM packages from Perl modules'
author:
  - 'Andreas Vögele <voegelas@cpan.org>'
build_requires:
  Test::MockObject: '0'
  Test::MockObject::Extends: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPANPLUS-Dist-Debora
provides:
  CPANPLUS::Dist::Debora:
    file: lib/CPANPLUS/Dist/Debora.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::License:
    file: lib/CPANPLUS/Dist/Debora/License.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Package:
    file: lib/CPANPLUS/Dist/Debora/Package.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Package::Debian:
    file: lib/CPANPLUS/Dist/Debora/Package/Debian.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Package::Mageia:
    file: lib/CPANPLUS/Dist/Debora/Package/Mageia.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Package::RPM:
    file: lib/CPANPLUS/Dist/Debora/Package/RPM.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Package::Tar:
    file: lib/CPANPLUS/Dist/Debora/Package/Tar.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Pod:
    file: lib/CPANPLUS/Dist/Debora/Pod.pm
    version: '0.010'
  CPANPLUS::Dist::Debora::Util:
    file: lib/CPANPLUS/Dist/Debora/Util.pm
    version: '0.010'
requires:
  Archive::Tar: '0'
  Archive::Tar::Constant: '0'
  CPAN::Meta: '0'
  CPANPLUS: '0.9166'
  CPANPLUS::Dist::Base: '0'
  CPANPLUS::Dist::Build: '0'
  CPANPLUS::Error: '0'
  Carp: '0'
  Cwd: '0'
  Encode: '0'
  English: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Spec::Unix: '0'
  File::Temp: '0'
  IPC::Cmd: '0'
  Module::CoreList: '2.32'
  Module::Pluggable: '0'
  Net::Domain: '0'
  POSIX: '0'
  Pod::Simple: '0'
  Pod::Simple::Search: '0'
  Scalar::Util: '0'
  Software::License: '0.103014'
  Software::LicenseUtils: '0.103014'
  Text::Template: '1.22'
  Text::Wrap: '0'
  parent: '0'
  perl: '5.016'
  utf8: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/voegelas/CPANPLUS-Dist-Debora/issues
  homepage: https://github.com/voegelas/CPANPLUS-Dist-Debora/wiki
  repository: https://github.com/voegelas/CPANPLUS-Dist-Debora.git
version: '0.010'
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
